[build]
builder = "NIXPACKS"
buildCommand = "npm install --include=dev && npm run build"

[deploy]
startCommand = "npm run start"
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyMaxRetries = 10
